"""Catalog onboarding drafts: static discovery to an accepted project.

Revision ID: 0009
Revises: 0008
Create Date: 2026-08-07

Sprint 5A's `github_repositories.onboarding_state` means "the GitHub
projection is complete". It deliberately says nothing about whether the
repository has been imported into Drake's project catalog — overloading it
would make provider readiness and catalog membership indistinguishable, and
they fail for entirely different reasons.

This migration adds a separate model for the catalog side:

- github_onboarding_drafts: one row per repository, carrying the immutable
  commit SHA a scan ran against, a bounded discovery summary, the manifest
  digest, and secret-free validation findings. It never stores repository
  file content, an invalid secret-bearing manifest body, or any credential.
- The repository/project binding is unique in BOTH directions, so a
  repository cannot be silently onboarded twice and two repositories cannot
  claim the same project.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Same bounded shape the Sprint 5A tables use for machine-readable codes.
_CODE_SHAPE = "~ '^[a-z0-9][a-z0-9_.-]{0,63}$'"


def upgrade() -> None:
    op.create_table(
        "github_onboarding_drafts",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "repository_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("github_repositories.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "scope_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("scopes.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        # The exact commit every file in this draft was read from. Nothing
        # is imported against "the default branch": a branch moves, a SHA
        # does not, and an import must describe a state that existed.
        sa.Column("commit_sha", sa.Text(), nullable=False, server_default=sa.text("''")),
        sa.Column("state", sa.Text(), nullable=False, server_default=sa.text("'not_started'")),
        # 'repository' = read from the repository at commit_sha and therefore
        # importable. 'operator_draft' = generated by Drake or edited in the
        # browser, and never importable (ADR-0007: the repository is the
        # source of intent).
        sa.Column("manifest_source", sa.Text(), nullable=False, server_default=sa.text("'none'")),
        # sha256 of the manifest text, so an import can prove it is
        # accepting the bytes that were reviewed.
        sa.Column("manifest_digest", sa.Text(), nullable=False, server_default=sa.text("''")),
        # Bounded, secret-free: file paths, sizes, digests, and detected
        # runtime/service evidence. Never file content.
        sa.Column(
            "discovery", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")
        ),
        # Validation findings carry path + rule + message only; the policy
        # layer guarantees no finding echoes a matched value.
        sa.Column(
            "findings", postgresql.JSONB(), nullable=False, server_default=sa.text("'[]'::jsonb")
        ),
        # The generated draft offered for download. Only ever a manifest
        # Drake itself composed from observed metadata — never repository
        # content, and never an invalid manifest read from a repository.
        sa.Column("draft_manifest", sa.Text(), nullable=True),
        sa.Column("reason_code", sa.Text(), nullable=True),
        sa.Column(
            "accepted_project_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("projects.id", ondelete="RESTRICT"),
            nullable=True,
        ),
        sa.Column("accepted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "accepted_by",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("identities.id", ondelete="RESTRICT"),
            nullable=True,
        ),
        sa.Column("scanned_at", sa.TIMESTAMP(timezone=True), nullable=True),
        # Optimistic concurrency: two admins reviewing the same repository
        # cannot import different revisions of the same draft.
        sa.Column("revision", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        # One live draft per repository: a rescan replaces what it found
        # rather than accumulating history nobody reads.
        sa.UniqueConstraint("repository_id", name="uq_github_onboarding_repository"),
        sa.CheckConstraint(
            "state IN ('not_started', 'scanning', 'needs_input', 'invalid', "
            "'ready_to_import', 'imported', 'failed')",
            name="ck_github_onboarding_state",
        ),
        sa.CheckConstraint(
            "manifest_source IN ('none', 'repository', 'operator_draft')",
            name="ck_github_onboarding_manifest_source",
        ),
        sa.CheckConstraint(
            "commit_sha = '' OR commit_sha ~ '^[0-9a-f]{40}$'",
            name="ck_github_onboarding_commit_sha",
        ),
        sa.CheckConstraint(
            f"reason_code IS NULL OR reason_code {_CODE_SHAPE}",
            name="ck_github_onboarding_reason_code",
        ),
        sa.CheckConstraint("revision >= 1", name="ck_github_onboarding_revision"),
        sa.CheckConstraint(
            "pg_column_size(discovery) <= 65536", name="ck_github_onboarding_discovery_bound"
        ),
        sa.CheckConstraint(
            "pg_column_size(findings) <= 65536", name="ck_github_onboarding_findings_bound"
        ),
        sa.CheckConstraint(
            "draft_manifest IS NULL OR length(draft_manifest) <= 131072",
            name="ck_github_onboarding_draft_bound",
        ),
        # An imported draft must say what it produced, and only a draft read
        # from the repository may reach that state.
        sa.CheckConstraint(
            "state <> 'imported' OR "
            "(accepted_project_id IS NOT NULL AND manifest_source = 'repository' "
            " AND commit_sha <> '')",
            name="ck_github_onboarding_imported_provenance",
        ),
    )
    op.create_index("ix_github_onboarding_scope", "github_onboarding_drafts", ["scope_id"])
    op.create_index("ix_github_onboarding_state", "github_onboarding_drafts", ["state"])

    # The accepted binding between a repository and a catalog project.
    # Unique in both directions: a repository cannot be onboarded into two
    # projects, and two repositories cannot claim the same project.
    op.create_table(
        "github_repository_projects",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "repository_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("github_repositories.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "project_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("projects.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "scope_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("scopes.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("commit_sha", sa.Text(), nullable=False),
        sa.Column("manifest_digest", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint("repository_id", name="uq_github_repository_project_repository"),
        sa.UniqueConstraint("project_id", name="uq_github_repository_project_project"),
        sa.CheckConstraint(
            "commit_sha ~ '^[0-9a-f]{40}$'", name="ck_github_repository_project_commit"
        ),
    )
    op.create_index(
        "ix_github_repository_projects_scope", "github_repository_projects", ["scope_id"]
    )


def downgrade() -> None:
    op.drop_table("github_repository_projects")
    op.drop_table("github_onboarding_drafts")
